apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nodejs
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "nikhildocker28/k8s-frontend:latest"
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort

